export default function Head() {
  return (
    <>
      <title>Reserve at  Milestone Grill | Opentable</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/public/restaurant-32.png" />
    </>
  )
}